// sites/app.campground.gg/src/routes/_global._campsite.c.$campId.t.$tentId/MemberSidebar.tsx
import { Stack, styled, Tabs, Typography } from "@mui/joy";
import { IconListTree, IconUsers } from "@tabler/icons-react";
import type { HttpResponseError } from "~/api/http/HTTPResponse";
import React, { type ContextType } from "react";
import MarkdownWrapper from "~/components/markdown/MarkdownWrapper";
import type { Session } from "~/context/session/types";
import type { MemberViewBasic } from "types/campground/membership";
import MemberList from "./MemberList";
import { CampsiteContext } from "../_global._campsite/context";
import { SmoothTabList } from "components";
import { FormattedMessageGlobal } from "~/i18n";
import type { TentViewBasic } from "types/campground/tent";

type Props = {
    campsiteId: string;
    tent: TentViewBasic;
    closed?: boolean;
} & React.PropsWithChildren;
type State = {
    loading: boolean;
    end: boolean;
    error: HttpResponseError | null;
    tab: number;
    members: MemberViewBasic[];
};

export const RightSidebarBox = styled(Stack, {
    name: "CampsiteSidebar",
    slot: "wrapper",
})(() => ({
    maxWidth: 320,
    gap: 4,
    height: "100%",
    transition: "width 0.3s",
    ".closed": {
        width: 0,
    },
}));
export const RightSidebarList = styled(Stack, {
    name: "CampsiteSidebar",
    slot: "root",
})(({ theme }) => ({
    backgroundColor: theme.vars.palette.background.surface,
    borderRadius: theme.vars.radius.xl,
    boxShadow: theme.vars.shadow.lg,
    border: `solid 1px ${theme.vars.palette.neutral.border}`,
    padding: 5,
}));

export default class MemberSidebar extends React.Component<
    Props,
    State
> {
    static contextType?: React.Context<any> | undefined = CampsiteContext;
    declare context: ContextType<typeof CampsiteContext>;

    private init: boolean = false;
    state: State = {
        loading: true,
        end: false,
        error: null,
        tab: 0,
        members: [],
    };
    constructor(props: Props, context: Session) {
        super(props, context);
    }
    async componentDidMount(): Promise<void> {
        if (this.init) return;

        this.init = true;

        return this.initFetchMembers();
    }
    async componentDidUpdate(
        _prevProps: Readonly<Props>,
        _prevState: Readonly<State>,
        _snapshot?: any,
    ): Promise<void> {
        if (this.init || !this.state.loading) return;
        // else if (_prevProps.tent.id !== this.props.tent.id)
        //     return this.initFetchMembers();

        return this.fetchMembers(this.state.members.length).then((x) => {
            if (!x.ok) return this.setState({ error: x, loading: false });

            return this.setState({
                members: [...this.state.members, ...x.content.members],
                end: x.content.members.length < 50,
                loading: false,
            });
        });
    }
    async initFetchMembers(): Promise<void> {
        return this.fetchMembers(0).then((resp) => {
            if (!resp.ok) return this.setState({ loading: false, error: resp });

            return this.setState({
                loading: false,
                members: resp.content.members,
                end: resp.content.members.length < 50,
            });
        });
    }
    async fetchMembers(offset: number) {
        return this.context.api.members.getMany(
            this.props.campsiteId,
            offset,
        );
    }
    render(): React.ReactNode {
        const { closed, tent, children } = this.props;

        return (
            <RightSidebarBox className={closed ? "closed" : ""}>
                {children && <RightSidebarList>{children}</RightSidebarList>}
                {tent.description && (
                    <RightSidebarList sx={{ px: 2, py: 1.5 }}>
                        <Typography level="title-md" fontWeight={700}>
                            <FormattedMessageGlobal id="info.topic" />
                        </Typography>
                        <MarkdownWrapper>{tent.description}</MarkdownWrapper>
                    </RightSidebarList>
                )}
                <RightSidebarList flex={1}>
                    <Tabs
                        onChange={(_, v) =>
                            this.setState({ tab: (v ?? 0) as number })
                        }
                        size="lg"
                        sx={{ mb: 1, borderRadius: "xl", overflow: "hidden" }}
                    >
                        <SmoothTabList
                            tabs={[
                                {
                                    id: 0,
                                    startDecorator: <IconUsers />,
                                    name: (
                                        <FormattedMessageGlobal id="app.members" />
                                    ),
                                },
                                {
                                    id: 1,
                                    startDecorator: <IconListTree />,
                                    name: (
                                        <FormattedMessageGlobal id="app.threads" />
                                    ),
                                },
                            ]}
                        />
                    </Tabs>
                    <CampsiteContext.Consumer>
                        {(ctx) => (
                            <MemberList
                                campsiteId={this.props.campsiteId}
                                memberCount={this.context.campsite.memberCount}
                                members={this.state.members}
                                roles={ctx.campsite.roles}
                            />
                        )}
                    </CampsiteContext.Consumer>
                </RightSidebarList>
            </RightSidebarBox>
        );
    }
}

// sites/app/src/routes/(global)/c/[campsite=campsite]/t/[tent=uuid]/Members/MemberSidebar.svelte
<script
	lang="ts"
	module
>
	import { defineMessages } from '@formatjs/svelte-intl';

	const messages = defineMessages({
		members: {
			id: 'app.members',
			defaultMessage: 'Members',
			description: 'Members pseudo-tent name, members tab in the right sidebar',
		},
		threads: {
			id: 'app.threads',
			defaultMessage: 'Threads',
			description: 'Message threads tab in the right sidebar',
		},
		topic: {
			id: 'info.topic',
			defaultMessage: 'Topic',
			description: 'Topic header in settings and tents',
		},
		noThreads: {
			id: 'app.threads.empty',
			defaultMessage: 'No threads yet',
			description: 'Empty state shown in the threads tab of the right sidebar',
		},
	});
</script>

<script lang="ts">
	import { LocaleMessage } from '@campground/locale';
	import { Card, Pick, TextBlock } from '@campground/ui';
	import { IconInfoCircle, IconListTree, IconUsers } from '@tabler/icons-svelte';
	import Markdown from '$lib/components/markdown/Markdown.svelte';
	import { UserDisplaySkeleton } from '$lib/components/users/index.js';
	import { getAppview } from '$lib/context/api.js';
	import type { GetMembersOutput, MemberViewBasic } from '$lib/types/campground/membership.js';
	import type { TentViewBasic } from '$lib/types/campground/tent.js';
	import { getCampsiteContext } from '../../../context.svelte.ts';
	import MemberList from './MemberList.svelte';

	const { tent }: { tent: TentViewBasic } = $props();

	const campsiteContext = getCampsiteContext();
	const campsite = $derived(campsiteContext.campsite);
	const appview = getAppview();

	let tab = $state(0);
	let members: MemberViewBasic[] = $state([]);
	let loading = $state(true);
	let reachedEnd = $state(false);

	function fetchMembers(offset: number): Promise<GetMembersOutput> {
		return campsite ? appview.members.getMany(campsite.id, offset) : Promise.resolve({ members: [] });
	}

	$effect(() => {
		if (!campsite) return;
		let invalidated = false;
		members = [];
		reachedEnd = false;
		loading = true;
		fetchMembers(0).then((output) => {
			if (invalidated) return;
			members = output.members;
			reachedEnd = output.members.length < 50;
			loading = false;
		});
		return () => {
			invalidated = true;
		};
	});

	function onScroll(ev: Event) {
		if (!campsite || loading || reachedEnd) return;
		const list = ev.currentTarget as HTMLDivElement;
		const remaining = list.scrollHeight - list.scrollTop - list.clientHeight;
		if (remaining > 128) return;
		loading = true;
		fetchMembers(members.length).then((output) => {
			members.push(...output.members);
			loading = false;
			reachedEnd = output.members.length < 50;
		});
	}
</script>

{#if campsite}
	<Card.Root
		level="subtle"
		size="xl"
	>
		<Card.Overflow flex={1}>
			<div class="inner">
				{#if tent.description}
					<div class="topic">
						<TextBlock weight={700}>
							<span class="topicHeader">
								<IconInfoCircle />
								<LocaleMessage {...messages.topic} />
							</span>
						</TextBlock>
						<Markdown value={tent.description} />
					</div>
				{/if}
				<Pick.Root
					value={tab}
					onChange={(value) => (tab = value)}
				>
					<Pick.List size="lg">
						<Pick.Item>
							<span class="tabLabel">
								<IconUsers />
								<LocaleMessage {...messages.members} />
							</span>
						</Pick.Item>
						<Pick.Item>
							<span class="tabLabel">
								<IconListTree />
								<LocaleMessage {...messages.threads} />
							</span>
						</Pick.Item>
					</Pick.List>
				</Pick.Root>
				<div
					class="list"
					onscroll={onScroll}
				>
					{#if tab === 0}
						{#if loading && !members.length}
							{#each Array(6).keys() as i (i)}
								<UserDisplaySkeleton size="sm" />
							{/each}
						{:else}
							<MemberList
								{members}
								roles={campsite.roles}
							/>
						{/if}
					{:else}
						<TextBlock level="subtext">
							<LocaleMessage {...messages.noThreads} />
						</TextBlock>
					{/if}
				</div>
			</div>
		</Card.Overflow>
	</Card.Root>
{/if}

<style lang="scss">
	.inner {
		display: flex;
		flex-direction: column;
		gap: 1rem;
		height: 100%;
	}

	.topic {
		padding: 0.25rem 0;
		border-bottom: solid 1px var(--neutral-border);
	}

	.topicHeader {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}

	.tabLabel {
		display: inline-flex;
		align-items: center;
		gap: 0.5rem;
	}

	.list {
		flex: 1;
		min-height: 0;
		overflow-y: auto;
	}
</style>
