// sites/app.campground.gg/src/routes/_global._campsite.c.$campId.t.$tentId/MemberList.tsx
import { Chip, List, Menu, Stack } from "@mui/joy";
import type { MemberViewBasic } from "types/campground/membership";
import type { RoleView } from "types/campground/roles";
import MemberItem from "./MemberItem";
import ContentCategory from "~/components/content/ContentCategory";
import { colorToDecimal } from "~/util/color";
import UserProfileCard from "~/layout/UserProfileCard";
import { useState, type MouseEvent } from "react";
import { GradientTypography } from "campground-ui";

type Props = {
    campsiteId: string;
    memberCount: number;
    members: MemberViewBasic[];
    roles: RoleView[];
};

export default function MemberList({ campsiteId, members, roles }: Props) {
    const displayedRoles = roles.filter((role) => role.raised);
    const defaultRole = roles.find((x) => x.flags & 1)!;
    const [cardMember, setCardMember] = useState<{
        x: number;
        y: number;
        member: MemberViewBasic;
    } | null>(null);

    // Make sure it always exists
    if (!defaultRole.raised) displayedRoles.push(defaultRole);

    const sortedMembers = members
        .sort((a, b) =>
            (a.nickname ?? a.user.displayName ?? a.user.did).localeCompare(
                b.nickname ?? b.user.displayName ?? b.user.did,
            ),
        )
        .map((member) => {
            // Single display role ensures no duplicates
            const displayedRole = displayedRoles.filter((role) =>
                member.roles.includes(role.id),
            )[0];

            return { member, displayedRole };
        });
    const groupRoles = displayedRoles
        .map((role) => ({ role, members: sortedMembers.filter((x) => x.displayedRole === role) }))
        .filter((x) => x.members.length);
    const displayMember = (
        ev: MouseEvent<HTMLDivElement>,
        member: MemberViewBasic,
    ) =>
        cardMember
            ? setCardMember(null)
            : setCardMember({
                    member,
                    x: document.body.clientWidth - 320,
                    y: ev.clientY + 8,
                });

    return (
        <>
            {cardMember && (
                <Menu
                    open
                    variant="soft"
                    style={{ top: cardMember.y, left: cardMember.x }}
                >
                    <UserProfileCard
                        did={cardMember.member.user.did}
                        user={cardMember.member.user}
                        member={cardMember.member}
                        campsiteRoles={roles}
                    />
                </Menu>
            )}
            <Stack gap={2}>
                {groupRoles.map(({ role, members }) => {
                    return (
                        <ContentCategory
                            key={role.id}
                            header={
                                <>
                                    <GradientTypography
                                        motion={role.motion}
                                        colors={colorToDecimal(role.colors)}
                                        level="title-md"
                                        fontWeight={700}
                                        sx={{ width: "max-content" }}
                                    >
                                        {role.name}
                                    </GradientTypography>
                                    <Chip
                                        variant="soft"
                                        sx={{ fontWeight: 700 }}
                                    >
                                        {members.length}
                                    </Chip>
                                </>
                            }
                        >
                            <List
                                sx={(theme) => ({
                                    "--List-padding": 0,
                                    "--ListItem-paddingY": "0.5rem",
                                    "--ListItem-radius": theme.vars.radius.md,
                                })}
                            >
                                {members.map(({ member }) => (
                                    <MemberItem
                                        key={member.user.did}
                                        campsiteId={campsiteId}
                                        member={member}
                                        roles={roles}
                                        onClick={(ev) =>
                                            displayMember(ev, member)
                                        }
                                    />
                                ))}
                            </List>
                        </ContentCategory>
                    );
                })}
            </Stack>
        </>
    );
}

// sites/app/src/routes/(global)/c/[campsite=campsite]/t/[tent=uuid]/Members/MemberList.svelte
<script lang="ts">
	import {
		Chip,
		Group,
		getMenuPortal,
		Menu,
		Section,
		type MenuPortalInstance,
	} from '@campground/ui';
	import { GradientText } from '@campground/ui';
	import UserCardMenu from '$lib/components/users/UserCardMenu.svelte';
	import type { MemberViewBasic } from '$lib/types/campground/membership.js';
	import type { RoleView } from '$lib/types/campground/roles.js';
	import { colorToDecimal } from '$lib/util/color.js';
	import MemberItem from './MemberItem.svelte';

	const { members, roles }: { members: MemberViewBasic[]; roles: RoleView[] } = $props();

	const displayedRoles = $derived.by(() => {
		const raised = roles.filter((role) => role.raised);
		const defaultRole = roles.find((x) => x.flags & 1) ?? roles[0];
		if (defaultRole && !raised.includes(defaultRole)) raised.push(defaultRole);
		return raised;
	});

	const groupRoles = $derived.by(() => {
		const sortedMembers = [...members].sort((a, b) =>
			(a.nickname ?? a.user.displayName ?? a.user.did).localeCompare(
				b.nickname ?? b.user.displayName ?? b.user.did,
			),
		);

		return displayedRoles
			.map((role) => ({
				role,
				members: sortedMembers.filter((member) => {
					const displayedRole = displayedRoles.find((x) => member.roles.includes(x.id));
					return displayedRole?.id === role.id;
				}),
			}))
			.filter((x) => x.members.length);
	});

	let cardMember: MemberViewBasic | null = $state(null);
	const menuPortal = getMenuPortal();

	function openMemberCard(
		ev: MouseEvent & { currentTarget: HTMLButtonElement },
		member: MemberViewBasic,
	) {
		cardMember = member;
		menuPortal.add(cardMenu, ev.currentTarget);
	}
</script>

{#snippet cardMenu(instance: MenuPortalInstance)}
	{#if cardMember}
		<Menu.Root
			{instance}
			placement="bottom-end"
			offset={8}
			w={20}
		>
			<UserCardMenu user={cardMember.user} />
		</Menu.Root>
	{/if}
{/snippet}

{#each groupRoles as { role, members: roleMembers } (role.id)}
	<Section
		gap="xs"
		headerLevel={4}
	>
		{#snippet header()}
			<Group gap={8}>
				<GradientText
					colors={colorToDecimal(role.colors)}
					motion={role.motion}
				>
					{role.name}
				</GradientText>
				<Chip size="sm">{roleMembers.length}</Chip>
			</Group>
		{/snippet}
		{#each roleMembers as member (member.user.did)}
			<MemberItem
				{member}
				{roles}
				onclick={openMemberCard}
			/>
		{/each}
	</Section>
{/each}
