// sites/app.campground.gg/src/routes/Index.tsx
import React from "react";
import { FormattedMessage } from "react-intl";
import IndexPageWrapper from "../components/index/IndexPageWrapper";
// import { Button, Group, SimpleGrid, Stack, Text } from "@mantine/core";
import { IconBrandDebian } from "@tabler/icons-react";
import { Button, Grid, Link, Stack, Typography } from "@mui/joy";
import PrimaryButton from "../components/PrimaryButton";

export type Props = {

};

export default class Index extends React.Component<Props> {
    constructor(props: Props) {
        super(props);
    }
    render() {
        return (
            <IndexPageWrapper>
                <Grid container sx={{ display: "grid", gridTemplateColumns: "5fr 4fr", gap: 5 }} spacing="xl" className="IndexPage top landing-side-padding landing-extreme-top">
                    <Grid gridColumn={1}>
                        <Stack direction="column" className="IndexPage top-motto">
                            <Grid container columns={{ xs: 1 }} gap={1} className="IndexPage top-motto-text">
                                <Grid>
                                    <Typography className="IndexPage top-motto-header" level="h1" fontSize={64} fontWeight={700}>
                                        <FormattedMessage id="home.title" />
                                    </Typography>
                                </Grid>
                                <Grid sx={{ mr: 6 }}>
                                    <Typography className="IndexPage top-motto-subtext" level="body-lg" textAlign="justify">
                                        <FormattedMessage id="home.description" />
                                    </Typography>
                                </Grid>
                            </Grid>
                            <Stack direction="row" className="IndexPage top-motto-buttons" gap={1}>
                                <Link underline="none" href="/download">
                                    <PrimaryButton size="lg" variant="solid" startDecorator={<IconBrandDebian />}>
                                        <FormattedMessage id="landing.download.debian" />
                                    </PrimaryButton>
                                </Link>
                                <Button variant="outlined" size="lg" component="a" href="/">
                                    <FormattedMessage id="global.openBrowser" />
                                </Button>
                            </Stack>
                        </Stack>
                    </Grid>
                </Grid>
            </IndexPageWrapper>
        );
    }
}

// sites/landing/src/routes/+page.svelte
<script lang="ts" module>
    const locale = defineMessages({
        'landing.inBrowser': {
            id: 'landing.inBrowser',
            defaultMessage: 'Open in Browser',
            description: 'Open Campground in browser button'
        }
    });
</script>
<script lang="ts">
	import { FormattedMessage, FormattedMessageGlobal } from "@campground/locale";

    import { Button, Para } from "@campground/ui";
	import { defineMessages } from "@formatjs/svelte-intl";
	import { IconBrandDebian } from "@tabler/icons-svelte";
</script>

<div class="Index container">
    <section class="Index initial">
        <div class="Index initial-left">
            <div class="Index motto">
                <Para level="h1" fontSize={3} letterSpacing={2.5}>
                    <FormattedMessageGlobal id="site.motto" />
                </Para>
                <Para level="paragraph" fontSize={1.25} letterSpacing={1} tMargin="md" align="justify">
                    <FormattedMessageGlobal id="site.desc" />
                </Para>
            </div>
            <div class="Index buttons">
                <a href="/download">
                    <Button size="lg">
                        <IconBrandDebian />
                        <FormattedMessageGlobal id="common.download" />
                    </Button>
                </a>
                <a href="/app">
                    <Button size="lg" variant="outlined">
                        <FormattedMessage {...locale['landing.inBrowser']} />
                    </Button>
                </a>
            </div>
        </div>
        <aside class="Index initial-right">
        </aside>
    </section>
</div>

<style lang="scss">
    .Index {
        &.container {
            padding: 0 var(--Layout-paddingX);
        }
        &.initial {
            height: calc(100vh - 72px);
            display: grid;
            grid-template-columns: 5fr 4fr;
        }
        &.initial-left {
            display: flex;
            flex-direction: column;
            
            padding-top: 128px;
            gap: 16px;
        }
        &.buttons {
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
            gap: 12px;
        }
        &.buttons > a {
            display: inline-flex;
            text-decoration: none;
        }
    }
</style>
