// packages/components/FlexCenter.tsx
import type { PropsWithChildren } from "react";
import { styled } from "@mui/joy";

type Props = PropsWithChildren;

const FlexCenterVertical = styled("div", {
    name: "FlexCenter",
    slot: "root",
})(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    height: "100%",
    width: "100%",
}));
const FlexCenterHorizontal = styled("div", {
    name: "FlexCenter",
    slot: "sub",
})(({ theme }) => ({
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    width: "100%",
}));

export default function FlexCenter({ children }: Props) {
    return (
        <FlexCenterVertical>
            <FlexCenterHorizontal>
                {children}
            </FlexCenterHorizontal>
        </FlexCenterVertical>
    )
}

// packages/ui/src/lib/FlexCenter/FlexCenter.svelte
<script lang="ts">
	import type FlexCenterProps from './props.ts';

	const { children, class: className }: FlexCenterProps = $props();
</script>

<div class={['FlexCenter', className]}>
	{@render children()}
</div>

<style lang="scss">
	.FlexCenter {
		display: flex;
		width: 100%;
		height: 100%;
		flex-direction: row;
		align-items: center;
		justify-content: center;
	}
</style>
