// sites/app.campground.gg/src/i18n/FormattedMessageGlobal.tsx
import { FormattedMessage } from "react-intl";
import globalIntlDeclarations from "./declarations";

type Props<T extends keyof typeof globalIntlDeclarations> = {
    id: T;
    values?: (typeof globalIntlDeclarations)[T] extends { values: infer V }
        ? V extends Record<string, any>
            ? V
            : never
        : never;
};

export default function FormattedMessageGlobal<
    T extends keyof typeof globalIntlDeclarations,
>({ id, values }: Props<T>) {
    return <FormattedMessage {...globalIntlDeclarations[id]} values={values} />;
}

// packages/locale/src/lib/FormattedMessageGlobal.svelte
<script lang="ts">
    import { globalLocale } from "./declarations.ts";
	import FormattedMessage from "./FormattedMessage/FormattedMessage.svelte";

    const { id, ...values }: { id: keyof typeof globalLocale } & Record<string, any> = $props();
</script>

<FormattedMessage {...globalLocale[id]} {...values} />
