// sites/app.campground.gg/src/components/form/FormSubmit.tsx
import { Button, type ButtonProps } from "@mui/joy";
import { FormattedMessageGlobal } from "~/i18n";
import { useForm } from "./context";

export default function FormSubmit({ children, variant, disabled, ...props }: Omit<ButtonProps, "onClick">) {
    const form = useForm();

    return (
        <Button disabled={disabled || !form.allValid} variant={variant ?? "glow"} {...props} onClick={form.onSubmit}>
            {children ?? <FormattedMessageGlobal id="form.submit" />}
        </Button>
    );
}

// packages/form/src/lib/FormSubmit/FormSubmit.svelte
<script lang="ts">
	import { FormattedMessageGlobal } from '@campground/locale';
	import { Button } from '@campground/ui';
	import type FormSubmitProps from './props.ts';
	import { getFormContext } from '$lib/Form/context.js';

	const { children, disabled, ...props }: FormSubmitProps = $props();

	let valid = $state(false);
	const formContext = getFormContext();

	formContext.fields.subscribe((values) => (valid = values.allValid));
</script>

<Button {...props} disabled={disabled || !valid} onclick={(ev) => formContext.submit(ev)}>
	{#if children}
		{@render children()}
	{:else}
		<FormattedMessageGlobal id="form.submit" />
	{/if}
</Button>
