// sites/app/src/routes/(global)/profile/[profile=didPlc]/ProfileFeedPost.svelte
<script
	lang="ts"
	module
>
	const messages = defineMessages({
		deletedPost: {
			id: 'app.profilePost.deletedParent',
			defaultMessage: 'The post has been deleted by the author or failed to be fetched.',
			description: 'Alert indicating that the parent post has been deleted',
		},
	});
</script>

<script lang="ts">
	import { ProfilePost } from '$lib/components/index.js';
	import type { ProfilePostViewParented } from '$lib/types/campground/user.js';
	import { LocaleMessage } from '@campground/locale';
	import { Alert, Threaded } from '@campground/ui';
	import { defineMessages } from '@formatjs/svelte-intl';
	import { IconTrashFilled } from '@tabler/icons-svelte';

	interface Props {
		profilePost: ProfilePostViewParented;
	}
	const { profilePost }: Props = $props();
</script>

{#if profilePost.parent || profilePost.parentUri}
	<Threaded.Root size="sm">
		{#snippet parent()}
			{#if profilePost.parent}
				<ProfilePost profilePost={profilePost.parent!} />
			{:else}
				<Alert color="warning">
					{#snippet icon()}
						<IconTrashFilled />
					{/snippet}
					<LocaleMessage {...messages.deletedPost} />
				</Alert>
			{/if}
		{/snippet}
		<Threaded.Item>
			<ProfilePost {profilePost} />
		</Threaded.Item>
	</Threaded.Root>
{:else}
	<ProfilePost {profilePost} />
{/if}

// sites/app/src/routes/_global.profile.$id/ProfileFeedPost.tsx
import { Alert, Box } from '@mui/joy';
import { useState } from 'react';
import { IconTrashFilled } from '@tabler/icons-react';
import type { EitherProfilePostView, ProfilePostViewParented } from 'types/campground/user';
import ProfilePost, { appearAnimation, ProfilePostSkeleton } from './ProfilePost';
import { ThreadLineItem, ThreadLineWrapper } from '~/components/ThreadLine';

type Props = {
	appear?: boolean;
	post: ProfilePostViewParented;
	isOwnPost?: boolean;
	onPostDelete: (uri: string) => void | Promise<any>;
	onPostUpdate: (uri: string, content: string) => void | Promise<any>;
};

export default function ProfileFeedPost(props: Props) {
	const { appear, isOwnPost } = props;
	const { parent, parentUri } = props.post as EitherProfilePostView;
	const [parentPost, setParentPost] = useState(parent);

	if (parentUri)
		return (
			<Box sx={{ animation: `${appearAnimation} ${appear ? 0.75 : 0}s` }}>
				<ThreadLineWrapper>
					{parent ?
						<ProfilePost
							showComments
							post={parentPost!}
							onPostUpdate={(_, content) => setParentPost({ ...parentPost!, content })}
							onPostDelete={() => setParentPost(null)}
						/>
					:	<Alert
							variant='soft'
							color='danger'
							startDecorator={<IconTrashFilled />}
						>
							This post has been deleted.
						</Alert>
					}
					<ThreadLineItem>
						<ProfilePost
							showComments
							isOwnPost={isOwnPost}
							onPostUpdate={props.onPostUpdate}
							onPostDelete={props.onPostDelete}
							post={props.post}
							mt={0.5}
						/>
					</ThreadLineItem>
				</ThreadLineWrapper>
			</Box>
		);

	return (
		<Box sx={{ animation: `${appearAnimation} ${appear ? 0.75 : 0}s` }}>
			<ProfilePost
				onPostUpdate={props.onPostUpdate}
				onPostDelete={props.onPostDelete}
				showComments
				post={props.post}
				isOwnPost={isOwnPost}
			/>
		</Box>
	);
}

export function ProfileFeedPostReplySkeleton() {
	return (
		<Box>
			<ThreadLineWrapper>
				<ProfilePostSkeleton />
				<ThreadLineItem>
					<ProfilePostSkeleton mt={0.5} />
				</ThreadLineItem>
			</ThreadLineWrapper>
		</Box>
	);
}
